console.log("Hello World")
console.log("Alexus")
console.log("My faviorite color is green")

let num1 = 4;
let num2 = 4;

let sum = num1 * num2;

console.log(sum)

let text1 = "Alexus";
let text2 = "Jones";

let result = text1.concat(" ", text2);
console.log(result)

for (let i= 1; i <=10;i++){
    console.log(i)
}

let text = "skillspire";
for (let i = 5; i < text.length;i++){
    console.log(text)
}

for(let i = 1; i<=10;i++){
    let result = i * 2

    console.log(result)
}

for (let i = 2; i <= 20; i += 2){
    console.log(i);
}

for(let i = 1; i<=19; i+=2){
    console.log(i)
}

for (let i = 1; i <= 10; i++) {
    if (i % 2 === 0) {
      console.log("FIZZ");
    } else {
      console.log("BUZZ");
    }
  }